-- SCHEMA: DaVinci
-- DROP SCHEMA "DaVinci" ;

CREATE SCHEMA "DaVinci" AUTHORIZATION postgres;
--
GRANT ALL ON SCHEMA "DaVinci" TO postgres WITH GRANT OPTION;
--
ALTER DEFAULT PRIVILEGES IN SCHEMA "DaVinci" GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;
--
ALTER DEFAULT PRIVILEGES IN SCHEMA "DaVinci" GRANT SELECT, USAGE ON SEQUENCES TO postgres WITH GRANT OPTION;
--
ALTER DEFAULT PRIVILEGES IN SCHEMA "DaVinci" GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;
--
ALTER DEFAULT PRIVILEGES IN SCHEMA "DaVinci" GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;
--